Cleaning Data

The exercise on preparing data for the model will be based on a single dataset. The heart_data set contains diagnostic information about one of the most important organs in the human body - the heart. The heart is an organ that constantly works at a high speed, performing about 100,000 beats and pumping 7200 liters of blood - every day. Based on medical parameters and the patient's own observations, it is possible to diagnose heart diseases. Our dataset contains the following information:

    age - the patient's age
    sex - gender of the patient
    chestpain - type of chest pain.
    trestbps - resting blood pressure (in mmHg).
    chol - cholesterol level (in mg/dl)
    fbs - fasting sugar level (if greater than 120 mg/dl, value "Y", opposite "N")
    restecg - the result of an electrocardiographic test.
    minhr - minimum measured heart rate
    maxhr - maximum measured heart rate
    exang - exercise-induced angina
    oldpeak - exercise-induced ST-segment depression relative to rest ("ST" is an element on the ECG graph)
    slope - the slope of the ST segment
    ca - number of major blood vessels
    thal - determines whether thalassemia (a genetic blood disease) is present
    ahd - determines if the patient has heart disease
1. Load data from the heart_data.csv file using the Pandas library.
2. Display the last 15 observations in the loaded data frame.
3. Remove variables that you think will be redundant to the model's prediction of heart disease.
4. Verify the presence of duplicates and remove them if present.
5. Verify the presence of blank values in the data. For numeric variables, fill in missing values with the median. Use any method.
6. Verify that values in categorical variables do not have errors. If there are inaccuracies, correct them.
7. Save the dataset to a .csv file. When saving, omit the index column (the index argument in the method that allows you to save the file to .csv).

In [64]:
import pandas as pd

heart_df = pd.read_csv("data/heart_data.csv")
heart_df.tail(15)

,age,sex,chestpain,restbp,chol,fbs,restecg,minhr,maxhr,exang,oldpeak,slope,ca,thal,ahd
298,45,Male,typical,110,264.0,No,0,NaN,132,No,1.2,2,0.0,reversable,Yes
299,68,Male,asymptomatic,144,193.0,Yes,0,NaN,141,No,3.4,2,2.0,reversable,Yes
300,57,Male,asymptomatic,130,131.0,No,0,NaN,115,Yes,1.2,2,1.0,reversable,Yes
301,57,Female,nontypical,130,236.0,No,2,NaN,174,No,0.0,2,1.0,normal,Yes
302,38,Male,nonanginal,138,175.0,No,0,NaN,173,No,0.0,1,NaN,normal,No
303,57,Male,asymptomatic,140,192.0,No,0,NaN,148,No,0.4,2,0.0,fixed,No
304,56,Female,nontypical,140,294.0,No,2,NaN,153,No,1.3,2,0.0,normal,No
305,56,Male,nonanginal,130,256.0,Yes,2,NaN,142,Yes,0.6,2,1.0,fixed,Yes
306,44,Male,nontypical,120,263.0,No,0,NaN,173,No,0.0,1,0.0,reversable,No
307,52,Male,nonanginal,172,199.0,Yes,0,NaN,162,No,0.5,1,0.0,reversable,No
308,57,Male,nonanginal,150,168.0,No,0,NaN,174,No,1.6,1,0.0,normal,No
309,48,Male,nontypical,110,229.0,No,0,NaN,168,No,1.0,3,0.0,reversable,Yes
310,54,Male,asymptomatic,140,239.0,No,0,NaN,160,No,1.2,1,0.0,normal,No
311,48,Female,nonanginal,130,275.0,No,0,NaN,139,No,0.2,1,0.0,normal,No
312,49,Male,nontypical,130,266.0,No,0,NaN,171,No,0.6,1,0.0,normal,No

In [65]:
# droping minhr column (all Null values)
heart_df = heart_df.drop(columns=["minhr"])
heart_df

,age,sex,chestpain,restbp,chol,fbs,restecg,maxhr,exang,oldpeak,slope,ca,thal,ahd
0,63,Male,typical,145,233.0,Yes,2,150,No,2.3,3,0.0,fixed,No
1,67,Male,asymptomatic,160,286.0,No,2,108,Yes,1.5,2,3.0,normal,Yes
2,67,Male,asymptomatic,120,229.0,No,2,129,Yes,2.6,2,2.0,reversable,Yes
3,37,Male,nonanginal,130,NaN,No,0,187,No,3.5,3,0.0,REversable,No
4,41,Female,nontypical,130,204.0,No,2,172,No,1.4,1,0.0,FIXED,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308,57,Male,nonanginal,150,168.0,No,0,174,No,1.6,1,0.0,normal,No
309,48,Male,nontypical,110,229.0,No,0,168,No,1.0,3,0.0,reversable,Yes
310,54,Male,asymptomatic,140,239.0,No,0,160,No,1.2,1,0.0,normal,No
311,48,Female,nonanginal,130,275.0,No,0,139,No,0.2,1,0.0,normal,No
312,49,Male,nontypical,130,266.0,No,0,171,No,0.6,1,0.0,normal,No

In [66]:
heart_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 313 entries, 0 to 312
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        313 non-null    int64
 1   sex        313 non-null    object
 2   chestpain  313 non-null    object
 3   restbp     313 non-null    int64
 4   chol       311 non-null    float64
 5   fbs        313 non-null    object
 6   restecg    313 non-null    int64
 7   maxhr      313 non-null    int64
 8   exang      313 non-null    object
 9   oldpeak    313 non-null    float64
 10  slope      313 non-null    int64
 11  ca         309 non-null    float64
 12  thal       311 non-null    object
 13  ahd        313 non-null    object
dtypes: float64(3), int64(5), object(6)
memory usage: 34.4+ KB

In [67]:
# check for duplicates
print(f"Number of duplicate rows before removal: {heart_df.duplicated().sum()}")
heart_df = heart_df.drop_duplicates()
print(f"Number of duplicate rows after removal: {heart_df.duplicated().sum()}")
heart_df

Number of duplicate rows before removal: 10
Number of duplicate rows after removal: 0

,age,sex,chestpain,restbp,chol,fbs,restecg,maxhr,exang,oldpeak,slope,ca,thal,ahd
0,63,Male,typical,145,233.0,Yes,2,150,No,2.3,3,0.0,fixed,No
1,67,Male,asymptomatic,160,286.0,No,2,108,Yes,1.5,2,3.0,normal,Yes
2,67,Male,asymptomatic,120,229.0,No,2,129,Yes,2.6,2,2.0,reversable,Yes
3,37,Male,nonanginal,130,NaN,No,0,187,No,3.5,3,0.0,REversable,No
4,41,Female,nontypical,130,204.0,No,2,172,No,1.4,1,0.0,FIXED,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,Male,typical,110,264.0,No,0,132,No,1.2,2,0.0,reversable,Yes
299,68,Male,asymptomatic,144,193.0,Yes,0,141,No,3.4,2,2.0,reversable,Yes
300,57,Male,asymptomatic,130,131.0,No,0,115,Yes,1.2,2,1.0,reversable,Yes
301,57,Female,nontypical,130,236.0,No,2,174,No,0.0,2,1.0,normal,Yes
302,38,Male,nonanginal,138,175.0,No,0,173,No,0.0,1,NaN,normal,No

Blank values

In [68]:
heart_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        303 non-null    int64
 1   sex        303 non-null    object
 2   chestpain  303 non-null    object
 3   restbp     303 non-null    int64
 4   chol       301 non-null    float64
 5   fbs        303 non-null    object
 6   restecg    303 non-null    int64
 7   maxhr      303 non-null    int64
 8   exang      303 non-null    object
 9   oldpeak    303 non-null    float64
 10  slope      303 non-null    int64
 11  ca         299 non-null    float64
 12  thal       301 non-null    object
 13  ahd        303 non-null    object
dtypes: float64(3), int64(5), object(6)
memory usage: 35.5+ KB

In [69]:
heart_df.isnull().sum()

age          0
sex          0
chestpain    0
restbp       0
chol         2
fbs          0
restecg      0
maxhr        0
exang        0
oldpeak      0
slope        0
ca           4
thal         2
ahd          0
dtype: int64

In [70]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy="median")

cat_cols = ["thal", "sex", "chestpain", "fbs", "exang", "ahd"]

heart_df_categorical = heart_df[cat_cols]

heart_df_numeric = heart_df.drop(columns=cat_cols)
heart_df_numeric = pd.DataFrame(
    imputer.fit_transform(heart_df_numeric),
    columns=imputer.get_feature_names_out()
)

heart_df = pd.concat([heart_df_numeric, heart_df_categorical], axis=1)
heart_df

,age,restbp,chol,restecg,maxhr,oldpeak,slope,ca,thal,sex,chestpain,fbs,exang,ahd
0,63.0,145.0,233.0,2.0,150.0,2.3,3.0,0.0,fixed,Male,typical,Yes,No,No
1,67.0,160.0,286.0,2.0,108.0,1.5,2.0,3.0,normal,Male,asymptomatic,No,Yes,Yes
2,67.0,120.0,229.0,2.0,129.0,2.6,2.0,2.0,reversable,Male,asymptomatic,No,Yes,Yes
3,37.0,130.0,240.0,0.0,187.0,3.5,3.0,0.0,REversable,Male,nonanginal,No,No,No
4,41.0,130.0,204.0,2.0,172.0,1.4,1.0,0.0,FIXED,Female,nontypical,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45.0,110.0,264.0,0.0,132.0,1.2,2.0,0.0,reversable,Male,typical,No,No,Yes
299,68.0,144.0,193.0,0.0,141.0,3.4,2.0,2.0,reversable,Male,asymptomatic,Yes,No,Yes
300,57.0,130.0,131.0,0.0,115.0,1.2,2.0,1.0,reversable,Male,asymptomatic,No,Yes,Yes
301,57.0,130.0,236.0,2.0,174.0,0.0,2.0,1.0,normal,Female,nontypical,No,No,Yes
302,38.0,138.0,175.0,0.0,173.0,0.0,1.0,0.0,normal,Male,nonanginal,No,No,No

In [71]:
heart_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        303 non-null    float64
 1   restbp     303 non-null    float64
 2   chol       303 non-null    float64
 3   restecg    303 non-null    float64
 4   maxhr      303 non-null    float64
 5   oldpeak    303 non-null    float64
 6   slope      303 non-null    float64
 7   ca         303 non-null    float64
 8   thal       301 non-null    object
 9   sex        303 non-null    object
 10  chestpain  303 non-null    object
 11  fbs        303 non-null    object
 12  exang      303 non-null    object
 13  ahd        303 non-null    object
dtypes: float64(8), object(6)
memory usage: 33.3+ KB

Verify that values in categorical variables do not have errors. If there are inaccuracies, correct them.

In [72]:
# column thal has 2 categorical missing values - deleted
heart_df = heart_df.dropna()
heart_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 301 entries, 0 to 302
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        301 non-null    float64
 1   restbp     301 non-null    float64
 2   chol       301 non-null    float64
 3   restecg    301 non-null    float64
 4   maxhr      301 non-null    float64
 5   oldpeak    301 non-null    float64
 6   slope      301 non-null    float64
 7   ca         301 non-null    float64
 8   thal       301 non-null    object
 9   sex        301 non-null    object
 10  chestpain  301 non-null    object
 11  fbs        301 non-null    object
 12  exang      301 non-null    object
 13  ahd        301 non-null    object
dtypes: float64(8), object(6)
memory usage: 35.3+ KB

In [73]:
# Save the cleaned dataset to a CSV file without the index column
heart_df.to_csv("data/heart_data_cleaned.csv", index=False)
print("Cleaned dataset saved to data/heart_data_cleaned.csv")

Cleaned dataset saved to data/heart_data_cleaned.csv