
Google Colab - exercise
On your Google Drive, create a "Machine Learning/Google Colab" folder into which you will upload the student_scores.csv file downloaded from the .zip at the beginning of the prework.
Start Google Colab and create a new notebook.
Write the code that will allow you to mount your Google Drive.
Check the version of the Pandas library installed on your machine.
From the mounted Google Drive, use the Pandas library to load the data into the framework.
Add a new column TotalScore to the data, which is the sum of the columns MathScore, ReadingScore, WritingScore.
Save the data frame to a file on a mounted Google Drive under the name colab_exercise.csv.
Save the Google Colab notebook file to disk as a python file (.py).

In [3]:
import pandas as pd

df = pd.read_csv('./data/student_scores.csv')
df

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,MathScore,ReadingScore,WritingScore
0,0,female,group B,bachelor's degree,standard,none,72,72,74
1,1,female,group C,some college,standard,completed,69,90,88
2,2,female,group B,master's degree,standard,none,90,95,93
3,3,male,group A,associate's degree,free/reduced,none,47,57,44
4,4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...,...
30636,995,male,group C,some high school,standard,none,56,47,51
30637,996,male,group E,associate's degree,free/reduced,none,74,75,72
30638,997,male,group C,some college,standard,none,36,29,27
30639,998,male,group A,some high school,free/reduced,completed,43,34,39
30640,999,female,group D,associate's degree,standard,none,52,68,66

In [5]:
df["TotalScore"] = df[["MathScore", "ReadingScore", "WritingScore"]].sum(axis=1)
df

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,MathScore,ReadingScore,WritingScore,TotalScore
0,0,female,group B,bachelor's degree,standard,none,72,72,74,218
1,1,female,group C,some college,standard,completed,69,90,88,247
2,2,female,group B,master's degree,standard,none,90,95,93,278
3,3,male,group A,associate's degree,free/reduced,none,47,57,44,148
4,4,male,group C,some college,standard,none,76,78,75,229
...,...,...,...,...,...,...,...,...,...,...
30636,995,male,group C,some high school,standard,none,56,47,51,154
30637,996,male,group E,associate's degree,free/reduced,none,74,75,72,221
30638,997,male,group C,some college,standard,none,36,29,27,92
30639,998,male,group A,some high school,free/reduced,completed,43,34,39,116
30640,999,female,group D,associate's degree,standard,none,52,68,66,186