Python (Pandas) - test exercise

Python – exercise (Pandas)
For the loans.csv dataset (from the zip package to download at the beginning of the prework), perform the following steps with the pandas library:

1. Import the library and, using the appropriate pandas library method, load the .csv file as a data frame.
2. Rename the columns so that each name consists of lowercase letters.
3. Display the first 10 observations in the dataset.
4. Check the types of the variables in the loaded data frame and perform type conversions where necessary.
5. Print a summary using the .isnull() method to see how many blank values are in each column.
6. For categorical variables, replace the blank values with the mode value (the most common value). Use the .mode() method to calculate the mode value for each column, and then insert it in the places with blank values.
7. For the loans_granted variable, assign a data frame that will contain data on those loans that have been granted to applicants.
8. For the standalone_borrowers variable, assign a data frame that will contain data on those loans that have been granted to standalone applicants.
9. For the loans_count_by_gender variable, assign a data frame that will specify:
The number of loans taken out by men and women
The average amount of income of the borrower
The average loan amount

Preparing and Cleaning Data

In [45]:
import pandas as pd

df_loans = pd.read_csv('./data/loans.csv')
df_loans

,Gender,Married,Dependents,Education,Self_Employed,Applicant_Income,Coapplicant_Income,Loan_Amount,Term,Credit_History,Area,Status
0,Male,No,0,Graduate,No,584900,0.0,15000000,360.0,1.0,Urban,Y
1,Male,Yes,1,Graduate,No,458300,150800.0,12800000,360.0,1.0,Rural,N
2,Male,Yes,0,Graduate,Yes,300000,0.0,6600000,360.0,1.0,Urban,Y
3,Male,Yes,0,Not Graduate,No,258300,235800.0,12000000,360.0,1.0,Urban,Y
4,Male,No,0,Graduate,No,600000,0.0,14100000,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
609,Female,No,0,Graduate,No,290000,0.0,7100000,360.0,1.0,Rural,Y
610,Male,Yes,3+,Graduate,No,410600,0.0,4000000,180.0,1.0,Rural,Y
611,Male,Yes,1,Graduate,No,807200,24000.0,25300000,360.0,1.0,Urban,Y
612,Male,Yes,2,Graduate,No,758300,0.0,18700000,360.0,1.0,Urban,Y
613,Female,No,0,Graduate,Yes,458300,0.0,13300000,360.0,0.0,Semiurban,N

In [46]:
df_loans.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'Applicant_Income', 'Coapplicant_Income', 'Loan_Amount', 'Term',
       'Credit_History', 'Area', 'Status'],
      dtype='object')

In [47]:
df_loans = df_loans.rename(columns=str.lower)
df_loans.head(10)

,gender,married,dependents,education,self_employed,applicant_income,coapplicant_income,loan_amount,term,credit_history,area,status
0,Male,No,0,Graduate,No,584900,0.0,15000000,360.0,1.0,Urban,Y
1,Male,Yes,1,Graduate,No,458300,150800.0,12800000,360.0,1.0,Rural,N
2,Male,Yes,0,Graduate,Yes,300000,0.0,6600000,360.0,1.0,Urban,Y
3,Male,Yes,0,Not Graduate,No,258300,235800.0,12000000,360.0,1.0,Urban,Y
4,Male,No,0,Graduate,No,600000,0.0,14100000,360.0,1.0,Urban,Y
5,Male,Yes,2,Graduate,Yes,541700,419600.0,26700000,360.0,1.0,Urban,Y
6,Male,Yes,0,Not Graduate,No,233300,151600.0,9500000,360.0,1.0,Urban,Y
7,Male,Yes,3+,Graduate,No,303600,250400.0,15800000,360.0,0.0,Semiurban,N
8,Male,Yes,2,Graduate,No,400600,152600.0,16800000,360.0,1.0,Urban,Y
9,Male,Yes,1,Graduate,No,1284100,1096800.0,34900000,360.0,1.0,Semiurban,N

In [48]:
df_loans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   gender              601 non-null    object
 1   married             611 non-null    object
 2   dependents          599 non-null    object
 3   education           614 non-null    object
 4   self_employed       582 non-null    object
 5   applicant_income    614 non-null    int64
 6   coapplicant_income  614 non-null    float64
 7   loan_amount         614 non-null    int64
 8   term                600 non-null    float64
 9   credit_history      564 non-null    float64
 10  area                614 non-null    object
 11  status              614 non-null    object
dtypes: float64(3), int64(2), object(7)
memory usage: 57.7+ KB

In [49]:
print(df_loans["dependents"].unique())
print(df_loans["gender"].unique())
print(df_loans["education"].unique())
print(df_loans["self_employed"].unique())

['0' '1' '2' '3+' nan]
['Male' 'Female' nan]
['Graduate' 'Not Graduate']
['No' 'Yes' nan]

In [50]:
missing_values = df_loans.isnull().sum()
print(missing_values)

gender                13
married                3
dependents            15
education              0
self_employed         32
applicant_income       0
coapplicant_income     0
loan_amount            0
term                  14
credit_history        50
area                   0
status                 0
dtype: int64

Fixing Data Types

In [51]:
# Fill categorical missing values with the mode
categorical_columns = [
    "gender",
    "married",
    "dependents",
    "self_employed",
    "education",
    "status",
    "area",
]

for column in categorical_columns:
    df_loans[column] = df_loans[column].fillna(df_loans[column].mode()[0])

# Check missing values after cleaning
print(df_loans.isnull().sum())

gender                 0
married                0
dependents             0
education              0
self_employed          0
applicant_income       0
coapplicant_income     0
loan_amount            0
term                  14
credit_history        50
area                   0
status                 0
dtype: int64

In [52]:
# Columns still having null values
print(df_loans[["term", "credit_history"]].isnull().sum())

term              14
credit_history    50
dtype: int64

In [53]:
df_loans[categorical_columns] = df_loans[categorical_columns].astype("string")
df_loans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   gender              614 non-null    string
 1   married             614 non-null    string
 2   dependents          614 non-null    string
 3   education           614 non-null    string
 4   self_employed       614 non-null    string
 5   applicant_income    614 non-null    int64
 6   coapplicant_income  614 non-null    float64
 7   loan_amount         614 non-null    int64
 8   term                600 non-null    float64
 9   credit_history      564 non-null    float64
 10  area                614 non-null    string
 11  status              614 non-null    string
dtypes: float64(3), int64(2), string(7)
memory usage: 57.7 KB

Filtering Data

In [54]:
loans_granted_df = df_loans.loc[
    (df_loans["status"]) == "Y"
]
print(loans_granted_df)
loans_granted_count = loans_granted_df["gender"].count()
print(f"Number of loans granted: {loans_granted_count}")

     gender married dependents     education self_employed  applicant_income  \
0      Male      No          0      Graduate            No            584900
2      Male     Yes          0      Graduate           Yes            300000
3      Male     Yes          0  Not Graduate            No            258300
4      Male      No          0      Graduate            No            600000
5      Male     Yes          2      Graduate           Yes            541700
..      ...     ...        ...           ...           ...               ...
608    Male     Yes          0      Graduate            No            323200
609  Female      No          0      Graduate            No            290000
610    Male     Yes         3+      Graduate            No            410600
611    Male     Yes          1      Graduate            No            807200
612    Male     Yes          2      Graduate            No            758300

     coapplicant_income  loan_amount   term  credit_history   area status
0                   0.0     15000000  360.0             1.0  Urban      Y
2                   0.0      6600000  360.0             1.0  Urban      Y
3              235800.0     12000000  360.0             1.0  Urban      Y
4                   0.0     14100000  360.0             1.0  Urban      Y
5              419600.0     26700000  360.0             1.0  Urban      Y
..                  ...          ...    ...             ...    ...    ...
608            195000.0     10800000  360.0             1.0  Rural      Y
609                 0.0      7100000  360.0             1.0  Rural      Y
610                 0.0      4000000  180.0             1.0  Rural      Y
611             24000.0     25300000  360.0             1.0  Urban      Y
612                 0.0     18700000  360.0             1.0  Urban      Y

[422 rows x 12 columns]
Number of loans granted: 422

In [55]:
standalone_borrowers_df = df_loans.loc[
    (df_loans["status"] == "Y") &
    (df_loans["dependents"] == str(0))
]
standalone_borrowers_df

,gender,married,dependents,education,self_employed,applicant_income,coapplicant_income,loan_amount,term,credit_history,area,status
0,Male,No,0,Graduate,No,584900,0.0,15000000,360.0,1.0,Urban,Y
2,Male,Yes,0,Graduate,Yes,300000,0.0,6600000,360.0,1.0,Urban,Y
3,Male,Yes,0,Not Graduate,No,258300,235800.0,12000000,360.0,1.0,Urban,Y
4,Male,No,0,Graduate,No,600000,0.0,14100000,360.0,1.0,Urban,Y
6,Male,Yes,0,Not Graduate,No,233300,151600.0,9500000,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
598,Male,Yes,0,Graduate,Yes,996300,0.0,18000000,360.0,1.0,Rural,Y
601,Male,Yes,0,Not Graduate,No,289400,279200.0,15500000,360.0,1.0,Rural,Y
603,Male,No,0,Graduate,No,367600,430100.0,17200000,360.0,1.0,Rural,Y
608,Male,Yes,0,Graduate,No,323200,195000.0,10800000,360.0,1.0,Rural,Y
609,Female,No,0,Graduate,No,290000,0.0,7100000,360.0,1.0,Rural,Y

Grouping Data for Insights

In [61]:
loans_by_gender = df_loans[['gender','applicant_income','loan_amount']].groupby(["gender"]).agg({
    'gender': 'count', 
    'applicant_income': 'mean',
    'loan_amount': 'mean'
    })
loans_by_gender.info()
loans_by_gender= loans_by_gender[['gender', 'applicant_income', 'loan_amount']].astype("int")
loans_by_gender

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, Female to Male
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            2 non-null      int64
 1   applicant_income  2 non-null      float64
 2   loan_amount       2 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 64.0+ bytes

        gender  applicant_income  loan_amount
gender
Female     112            464347     12330357
Male       502            557301     14545019