# Dataset normalization

In the sheets of the **dims.xlsx** file there are dictionaries for the data from the **product_prices_cleaned.csv** file. Use `merge` to normalize the data following the steps:

1. Read the contents of the **dims.xlsx** file sheets to separate `DataFrames`.
For readability base names of frames on the names of sheets.

1. Read the data from **product_prices_cleaned.csv** file to the `df` variable.

1. Based on the **d_province** workbook, use the `id` column to add the `province_id` column to the `df` frame.

1. Based on the  **d_product** workbook, add the `product_id` column to the `df` frame.

1. From the table, extract only the columns that refer to other tables, e.g.. **product_id** and the columns **value**, **date**. Do you think this is more readable? What are potential benefits of this approach?

> We will tell you how to read many workbooks at once when we discuss `openpyxl`.

You can find more about database normalization at the [link](https://www.sqlshack.com/what-is-database-normalization-in-sql-server/).

In [34]:
import pandas as pd

df = pd.read_csv(
    r'C:\Users\UrosVukmanovic\CodersLab-Course-Python-Data-Analysis\Python Session_3\Session_3_-_exercise_files\01_Data\product_prices_cleaned_2.csv',
    sep=';',
    encoding='UTF-8',
    decimal='.'
)
df

C:\Users\UrosVukmanovic\AppData\Local\Temp\ipykernel_40556\111081364.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

,province,product_types,currency,product_group_id,product_line,value,date,product
0,SUBCARPATHIA,NaN,PLN,2.0,pork ham cooked - per 1kg,21.37,2013-3,pork ham cooked - per 1kg
1,ŁÓDŹ,NaN,PLN,4.0,bread - per 1kg,NaN,2018-2,bread - per 1kg
2,KUYAVIA-POMERANIA,NaN,PLN,2.0,barley groats sausage - per 1kg,3.55,2019-12,barley groats sausage - per 1kg
3,LOWER SILESIA,NaN,PLN,2.0,dressed chickens - per 1kg,6.14,2019-2,dressed chickens - per 1kg
4,WARMIA-MASURIA,NaN,PLN,2.0,Italian head cheese - per 1kg,5.63,2002-3,Italian head cheese - per 1kg
...,...,...,...,...,...,...,...,...
132247,KUYAVIA-POMERANIA,NaN,PLN,2.0,pork meat (raw bacon) - per 1kg,12.15,2016-11,pork meat (raw bacon) - per 1kg
132248,ŁÓDŹ,"beet sugar white, bagged - per 1kg",PLN,3.0,NaN,0.0,2012-5,"beet sugar white, bagged - per 1kg"
132249,LESSER POLAND,NaN,PLN,4.0,plain mixed bread (wheat-rye) - per 1kg,3.05,2008-6,plain mixed bread (wheat-rye) - per 1kg
132250,WARMIA-MASURIA,NaN,PLN,2.0,boneless beef (sirloin) - per 1kg,11.87,2000-11,boneless beef (sirloin) - per 1kg
132251,NaN,NaN,NaN,NaN,NaN,PLN,NaN,NaN

In [35]:
df.loc[
    ~(df['province'] == 'POLSKA') &
    ~(df['province'] == 'POLAND') &
    (df['province'].notnull()) &
    ~(df['value'] == 0) &
    ~(df['value'] == 3000) &
    (df['value'].notnull())     
    ]
df

,province,product_types,currency,product_group_id,product_line,value,date,product
0,SUBCARPATHIA,NaN,PLN,2.0,pork ham cooked - per 1kg,21.37,2013-3,pork ham cooked - per 1kg
1,ŁÓDŹ,NaN,PLN,4.0,bread - per 1kg,NaN,2018-2,bread - per 1kg
2,KUYAVIA-POMERANIA,NaN,PLN,2.0,barley groats sausage - per 1kg,3.55,2019-12,barley groats sausage - per 1kg
3,LOWER SILESIA,NaN,PLN,2.0,dressed chickens - per 1kg,6.14,2019-2,dressed chickens - per 1kg
4,WARMIA-MASURIA,NaN,PLN,2.0,Italian head cheese - per 1kg,5.63,2002-3,Italian head cheese - per 1kg
...,...,...,...,...,...,...,...,...
132247,KUYAVIA-POMERANIA,NaN,PLN,2.0,pork meat (raw bacon) - per 1kg,12.15,2016-11,pork meat (raw bacon) - per 1kg
132248,ŁÓDŹ,"beet sugar white, bagged - per 1kg",PLN,3.0,NaN,0.0,2012-5,"beet sugar white, bagged - per 1kg"
132249,LESSER POLAND,NaN,PLN,4.0,plain mixed bread (wheat-rye) - per 1kg,3.05,2008-6,plain mixed bread (wheat-rye) - per 1kg
132250,WARMIA-MASURIA,NaN,PLN,2.0,boneless beef (sirloin) - per 1kg,11.87,2000-11,boneless beef (sirloin) - per 1kg
132251,NaN,NaN,NaN,NaN,NaN,PLN,NaN,NaN

In [36]:
d_province = pd.read_excel(
    r'C:\Users\UrosVukmanovic\CodersLab-Course-Python-Data-Analysis\Python Session_3\Session_3_-_exercise_files\01_Data\dims.xlsx',
    sheet_name='d_province'
)

In [37]:
d_product_group = pd.read_excel(
    r'C:\Users\UrosVukmanovic\CodersLab-Course-Python-Data-Analysis\Python Session_3\Session_3_-_exercise_files\01_Data\dims.xlsx',
    sheet_name='d_product_group'
)

In [38]:


d_product = pd.read_excel(
    r'C:\Users\UrosVukmanovic\CodersLab-Course-Python-Data-Analysis\Python Session_3\Session_3_-_exercise_files\01_Data\dims.xlsx',
    sheet_name='d_product'
)

d_product.head()

   product_id                          product  product_group_id
0          20        pork ham cooked - per 1kg                 2
1          26                  bread - per 1kg                 4
2          10  barley groats sausage - per 1kg                 2
3          12       dressed chickens - per 1kg                 2
4          19    Italian head cheese - per 1kg                 2

Province Column Normalization

In [39]:
df = pd.merge(
    left = df,
    right= d_province,
    on=['province']
)
df.head()

,province,product_types,currency,product_group_id,product_line,value,date,product,province_id
0,SUBCARPATHIA,NaN,PLN,2.0,pork ham cooked - per 1kg,21.37,2013-3,pork ham cooked - per 1kg,8
1,ŁÓDŹ,NaN,PLN,4.0,bread - per 1kg,NaN,2018-2,bread - per 1kg,14
2,KUYAVIA-POMERANIA,NaN,PLN,2.0,barley groats sausage - per 1kg,3.55,2019-12,barley groats sausage - per 1kg,2
3,LOWER SILESIA,NaN,PLN,2.0,dressed chickens - per 1kg,6.14,2019-2,dressed chickens - per 1kg,1
4,WARMIA-MASURIA,NaN,PLN,2.0,Italian head cheese - per 1kg,5.63,2002-3,Italian head cheese - per 1kg,11

In [40]:
df = pd.merge(
    left = df,
    right = d_product,
    on = ['product', 'product_group_id']
)

df.head()

,province,product_types,currency,product_group_id,product_line,value,date,product,province_id,product_id
0,SUBCARPATHIA,NaN,PLN,2.0,pork ham cooked - per 1kg,21.37,2013-3,pork ham cooked - per 1kg,8,20
1,ŁÓDŹ,NaN,PLN,4.0,bread - per 1kg,NaN,2018-2,bread - per 1kg,14,26
2,KUYAVIA-POMERANIA,NaN,PLN,2.0,barley groats sausage - per 1kg,3.55,2019-12,barley groats sausage - per 1kg,2,10
3,LOWER SILESIA,NaN,PLN,2.0,dressed chickens - per 1kg,6.14,2019-2,dressed chickens - per 1kg,1,12
4,WARMIA-MASURIA,NaN,PLN,2.0,Italian head cheese - per 1kg,5.63,2002-3,Italian head cheese - per 1kg,11,19

In [41]:
df = pd.merge(
    left=df,
    right=d_product_group,
    on=['product_group_id']
)
df.head()

,province,product_types,currency,product_group_id,product_line,value,date,product,province_id,product_id,product_group
0,SUBCARPATHIA,NaN,PLN,2.0,pork ham cooked - per 1kg,21.37,2013-3,pork ham cooked - per 1kg,8,20,meat products
1,ŁÓDŹ,NaN,PLN,4.0,bread - per 1kg,NaN,2018-2,bread - per 1kg,14,26,oat products
2,KUYAVIA-POMERANIA,NaN,PLN,2.0,barley groats sausage - per 1kg,3.55,2019-12,barley groats sausage - per 1kg,2,10,meat products
3,LOWER SILESIA,NaN,PLN,2.0,dressed chickens - per 1kg,6.14,2019-2,dressed chickens - per 1kg,1,12,meat products
4,WARMIA-MASURIA,NaN,PLN,2.0,Italian head cheese - per 1kg,5.63,2002-3,Italian head cheese - per 1kg,11,19,meat products

In [42]:
df[[
    'province_id',
    'product_id',
    'product_group_id',
    'value',
    'date'
]]

        province_id  product_id  product_group_id  value     date
0                 8          20               2.0  21.37   2013-3
1                14          26               4.0    NaN   2018-2
2                 2          10               2.0   3.55  2019-12
3                 1          12               2.0   6.14   2019-2
4                11          19               2.0   5.63   2002-3
...             ...         ...               ...    ...      ...
120442           15          10               2.0    4.5   2004-8
120443            2          13               2.0  12.15  2016-11
120444           14          22               3.0    0.0   2012-5
120445            6          27               4.0   3.05   2008-6
120446           11          16               2.0  11.87  2000-11

[120447 rows x 5 columns]