# Modification of column names

Read the file **product_prices.csv** into a DataFrame. Modify the names of columns so that they match those in the  **product_prices_renamed.csv** file. Complete two variants of the exercise:

1. Using the `rename` method,
1. Overwriting all column names using `columns`.

To unify the naming and reduce the risk of a **typo**, you can use the dictionary below:
```
{'Name': 'province',
 'Types of goods': 'product_types',
 'Measurement unit': 'currency',
 'id': 'id',
 'Types of products': 'product_line',
 'Value': 'value',
 'Date': 'date'}
```

> The `columns` method overwrites the columns directly on the object (does not return a new DataFrame), so if you do step 2 first, the hint will be useless (the columns get overwritten).

In [5]:
import pandas as pd

df = pd.read_csv(
    r'C:\Users\UrosVukmanovic\CodersLab-Course-Python-Data-Analysis\Python Session_3\Session_3_-_exercise_files\01_Data\product_prices.csv',
    sep=';',
    encoding='UTF-8',
    decimal='.'
)

print(df)

                     Name                         Goods types  \
0            SUBCARPATHIA                                 NaN
1                    ŁÓDŹ                                 NaN
2       KUYAVIA-POMERANIA                                 NaN
3           LOWER SILESIA                                 NaN
4          WARMIA-MASURIA                                 NaN
...                   ...                                 ...
149935  KUYAVIA-POMERANIA                                 NaN
149936               ŁÓDŹ  beet sugar white, bagged - per 1kg
149937      LESSER POLAND                                 NaN
149938     WARMIA-MASURIA                                 NaN
149939            MASOVIA                                 NaN

       Measurement unit  Group ID                            Product types  \
0                   PLN         2                pork ham cooked - per 1kg
1                   PLN         4                          bread - per 1kg
2                   PLN         2          barley groats sausage - per 1kg
3                   PLN         2               dressed chickens - per 1kg
4                   PLN         2            Italian head cheese - per 1kg
...                 ...       ...                                      ...
149935              PLN         2         pork  meat (raw bacon) - per 1kg
149936              PLN         3                                      NaN
149937              PLN         4  plain mixed bread (wheat-rye) - per 1kg
149938              PLN         2        boneless beef (sirloin) - per 1kg
149939              PLN         4         Masurian barley groats - per 1kg

        Value     Date
0       21.37   2013-3
1         NaN   2018-2
2        3.55  2019-12
3        6.14   2019-2
4        5.63   2002-3
...       ...      ...
149935  12.15  2016-11
149936   0.00   2012-5
149937   3.05   2008-6
149938  11.87  2000-11
149939   0.16  2005-10

[149940 rows x 7 columns]

In [6]:
cols_new = {'Name': 'province',
 'Types of goods': 'product_types',
 'Measurement unit': 'currency',
 'id': 'id',
 'Types of products': 'product_line',
 'Value': 'value',
 'Date': 'date'}

df.rename(columns=cols_new)

,province,Goods types,currency,Group ID,Product types,value,date
0,SUBCARPATHIA,NaN,PLN,2,pork ham cooked - per 1kg,21.37,2013-3
1,ŁÓDŹ,NaN,PLN,4,bread - per 1kg,NaN,2018-2
2,KUYAVIA-POMERANIA,NaN,PLN,2,barley groats sausage - per 1kg,3.55,2019-12
3,LOWER SILESIA,NaN,PLN,2,dressed chickens - per 1kg,6.14,2019-2
4,WARMIA-MASURIA,NaN,PLN,2,Italian head cheese - per 1kg,5.63,2002-3
...,...,...,...,...,...,...,...
149935,KUYAVIA-POMERANIA,NaN,PLN,2,pork meat (raw bacon) - per 1kg,12.15,2016-11
149936,ŁÓDŹ,"beet sugar white, bagged - per 1kg",PLN,3,NaN,0.00,2012-5
149937,LESSER POLAND,NaN,PLN,4,plain mixed bread (wheat-rye) - per 1kg,3.05,2008-6
149938,WARMIA-MASURIA,NaN,PLN,2,boneless beef (sirloin) - per 1kg,11.87,2000-11
149939,MASOVIA,NaN,PLN,4,Masurian barley groats - per 1kg,0.16,2005-10

In [7]:
df.rename(columns = {
    'Name': 'province',
    'Goods types': 'product_types',
    'Measurement unit': 'currency',
    'Group ID': 'product_group_id',
    'Product types': 'product_line',
    'Value': 'value',
    'Date': 'date'
})

,province,product_types,currency,product_group_id,product_line,value,date
0,SUBCARPATHIA,NaN,PLN,2,pork ham cooked - per 1kg,21.37,2013-3
1,ŁÓDŹ,NaN,PLN,4,bread - per 1kg,NaN,2018-2
2,KUYAVIA-POMERANIA,NaN,PLN,2,barley groats sausage - per 1kg,3.55,2019-12
3,LOWER SILESIA,NaN,PLN,2,dressed chickens - per 1kg,6.14,2019-2
4,WARMIA-MASURIA,NaN,PLN,2,Italian head cheese - per 1kg,5.63,2002-3
...,...,...,...,...,...,...,...
149935,KUYAVIA-POMERANIA,NaN,PLN,2,pork meat (raw bacon) - per 1kg,12.15,2016-11
149936,ŁÓDŹ,"beet sugar white, bagged - per 1kg",PLN,3,NaN,0.00,2012-5
149937,LESSER POLAND,NaN,PLN,4,plain mixed bread (wheat-rye) - per 1kg,3.05,2008-6
149938,WARMIA-MASURIA,NaN,PLN,2,boneless beef (sirloin) - per 1kg,11.87,2000-11
149939,MASOVIA,NaN,PLN,4,Masurian barley groats - per 1kg,0.16,2005-10

In [8]:
df.columns = list(cols_new.values())
df

,province,product_types,currency,id,product_line,value,date
0,SUBCARPATHIA,NaN,PLN,2,pork ham cooked - per 1kg,21.37,2013-3
1,ŁÓDŹ,NaN,PLN,4,bread - per 1kg,NaN,2018-2
2,KUYAVIA-POMERANIA,NaN,PLN,2,barley groats sausage - per 1kg,3.55,2019-12
3,LOWER SILESIA,NaN,PLN,2,dressed chickens - per 1kg,6.14,2019-2
4,WARMIA-MASURIA,NaN,PLN,2,Italian head cheese - per 1kg,5.63,2002-3
...,...,...,...,...,...,...,...
149935,KUYAVIA-POMERANIA,NaN,PLN,2,pork meat (raw bacon) - per 1kg,12.15,2016-11
149936,ŁÓDŹ,"beet sugar white, bagged - per 1kg",PLN,3,NaN,0.00,2012-5
149937,LESSER POLAND,NaN,PLN,4,plain mixed bread (wheat-rye) - per 1kg,3.05,2008-6
149938,WARMIA-MASURIA,NaN,PLN,2,boneless beef (sirloin) - per 1kg,11.87,2000-11
149939,MASOVIA,NaN,PLN,4,Masurian barley groats - per 1kg,0.16,2005-10