# Python Test

### Instructions

Welcome to the Pandas Test!

The goal of this test is to assess your current knowledge and skills in manipulating data using the Pandas library. The test contains 4 basic tasks (ordered by difficulty) and one additional, bonus task that is not mandatory, but recommended for more advanced candidates. Each task carries a certain number of points, the maximum possible score is 5 points.

Use this notebook to solve the tasks. It is your responsibility to set up the necessary environment and install all libraries. For each task, write your solutions in the cell below the task description.

Send your solutions via slack message or email. Good luck!

### Tasks

In [104]:
import pandas as pd

data = {
    "Student": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Helen", "Ian", "Jack"],
    "Math": [85, 90, 78, 88, 92, 76, 81, 95, 89, 84],
    "Science": [91, 85, 80, 94, 88, 79, 87, 92, 90, 83],
    "English": [88, 92, 85, 91, 93, 78, 84, 89, 86, 80],
    "History": [90, 88, 85, 91, 95, 82, 80, 87, 88, 86],
    "Art": [92, 79, 84, 87, 90, 88, 92, 85, 83, 90]
}

df = pd.DataFrame(data)
df

   Student  Math  Science  English  History  Art
0    Alice    85       91       88       90   92
1      Bob    90       85       92       88   79
2  Charlie    78       80       85       85   84
3    David    88       94       91       91   87
4      Eve    92       88       93       95   90
5    Frank    76       79       78       82   88
6    Grace    81       87       84       80   92
7    Helen    95       92       89       87   85
8      Ian    89       90       86       88   83
9     Jack    84       83       80       86   90

1. For the given dataframe `df`, calculate the median score for each subject (Math, Science, English, History, and Art). (0.5p)

In [105]:
df[['Math', 'Science', 'English', 'History', 'Art']].mean()

# svaki element liste daje prosek tog elementa. kada se napisu 2 zagrade pravi se novi dataframe i za svaki se dobija series sa prosecima

Math       85.8
Science    86.9
English    86.6
History    87.2
Art        87.0
dtype: float64

2. Create a new dataframe `df_good_in_math` that contains only the students who have scored greater than 85 in Math. (1p)

In [106]:
df_good_in_math = df.loc[
    (df['Math'] > 85)
     ]
df_good_in_math

# Sa df.loc funkcijom filtriramo df i izdvajamo samo studente koji zadovoljavaju uslov df['Math'] > 85

  Student  Math  Science  English  History  Art
1     Bob    90       85       92       88   79
3   David    88       94       91       91   87
4     Eve    92       88       93       95   90
7   Helen    95       92       89       87   85
8     Ian    89       90       86       88   83

3. Write a function that calculates and returns the correlation coefficient between the `Math` and `Science` scores. Explain the correlation score. (1.5p)

In [107]:
def correlation_coef(df):
    corr = df['Math'].corr(df['Science'])
    return corr

correlation_coef(df)

np.float64(0.731773680652004)

koristimo postojecu df metodu .corr kojoj predajemo data frame od izdvojene kolone science i vracamo iz funkcije rez
Correlation explanation: 0.73 je koeficijent korelacije sto nam govori da postoji odredjena linearna korelacija izmedju ovih predmeta.
Rezultat je ocekivan zbog toga sto pripadaju istoj grupi predmeta - prirodnjacki, manja verovatnoca je je da ocene iz drustevnih i prirodnih nauka budu korelisane

4. In the given dataframe `df`, add new column `total` that calculates the total score for each student (sum of scores in all subjects) and print the name of the student with the highest total score. (2p)

In [127]:
dflist = ['Math', 'Science', 'English', 'History', 'Art'] # lista kolona sa ocenama za sum
df['total'] = df[dflist].sum(axis=1) # pravimo kolonu total tako sto sumiramo novi df - df[dflist] axis=1 =row wise sum
df_sorted = df.sort_values(by='total', ascending=False) # sortiramo prema kololin total descending - najbolji ka najlosijem rezultatu
df_sorted

   Student  Math  Science  English  History  Art  total
4      Eve    92       88       93       95   90    458
3    David    88       94       91       91   87    451
7    Helen    95       92       89       87   85    448
0    Alice    85       91       88       90   92    446
8      Ian    89       90       86       88   83    436
1      Bob    90       85       92       88   79    434
6    Grace    81       87       84       80   92    424
9     Jack    84       83       80       86   90    423
2  Charlie    78       80       85       85   84    412
5    Frank    76       79       78       82   88    403

In [135]:
top_student = df.loc[df['total'].idxmax(), 'Student'] # filtriramo samo top studenta i prikazujemo samo ime naznakom na kolonu 'Student'
print(top_student)

Eve

Mana resenja je to sto sam listu predmeta hardcodovao u objekat dflist, bolje resenje bi bilo da se prodje kroz ceo dataframe i da kolko god predmeta ima da se napravi lista automatski

- Bonus task: Transform the dataframe so that each student could be in several rows, but one row for each subject. Print the data, and then return it to the original format with the following transformation. (2p)

In [ ]:
# wide -> long (subjects in one column) and back to wide
subjects = ['Math', 'Science', 'English', 'History', 'Art']
# wide -> long
df_long = df.melt(id_vars='Student', value_vars=subjects, var_name='Subject', value_name='Score')
print('Long format (first rows):')
print(df_long.head().to_string(index=False))

# pivot subjects as rows, students as columns
pivot_subjects_rows = df_long.pivot(index='Subject', columns='Student', values='Score')
print('\nPivot (Subjects as rows, Students as columns):')
print(pivot_subjects_rows)

# reconstruct wide format (students as rows, subjects as columns)
df_reconstructed = df_long.pivot(index='Student', columns='Subject', values='Score').reset_index()
df_reconstructed = df_reconstructed[['Student'] + subjects]
print('\nReconstructed wide format (first rows):')
print(df_reconstructed.head().to_string(index=False))

Long format (first rows):
Student Subject  Score
  Alice    Math     85
    Bob    Math     90
Charlie    Math     78
  David    Math     88
    Eve    Math     92

Pivot (Subjects as rows, Students as columns):
Student  Alice  Bob  Charlie  David  Eve  Frank  Grace  Helen  Ian  Jack
Subject
Art         92   79       84     87   90     88     92     85   83    90
English     88   92       85     91   93     78     84     89   86    80
History     90   88       85     91   95     82     80     87   88    86
Math        85   90       78     88   92     76     81     95   89    84
Science     91   85       80     94   88     79     87     92   90    83

Reconstructed wide format (first rows):
Student  Math  Science  English  History  Art
  Alice    85       91       88       90   92
    Bob    90       85       92       88   79
Charlie    78       80       85       85   84
  David    88       94       91       91   87
    Eve    92       88       93       95   90