# Formatting dates

Load the _product_prices_cleaned.csv_ file, the _date_ column contains information about the months of value reporting.

1. What date format is it?
1. Change the column format to `datetime64`.
1. Add a new column – _month_ to the DataFrame as a way to isolate the information about the month from the _date_ column.
1. Add a new column – _quarter_ to the DataFrame as a way to isolate the information about the quarter from the _date_ column,
1. Add a new column – _year_ to the DataFrame as a way to isolate the information about the year from the _date_ column,
1. Using the `dt.strfime` method ([link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.dt.strftime.html) to the documentation), convert the  _date_ column to the _YYYY-MM-01_ format and overwrite its value; e.g.:
```
df['date'] = col.dt.strftime('format')
```
1. Overwrite the _product_prices_cleaned.csv_ file. It will be used in the following sections to analyze the collection.

In [30]:
import pandas as pd
path = r'C:\Users\UrosVukmanovic\CodersLab-Course-Python-Data-Analysis\Python Session_3\Session_3_-_exercise_files\01_Data\product_prices_cleaned_2.csv'

df = pd.read_csv(path, sep=';', encoding='UTF-8', decimal='.')

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132252 entries, 0 to 132251
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   province          132251 non-null  object
 1   product_types     34272 non-null   object
 2   currency          132251 non-null  object
 3   product_group_id  132251 non-null  float64
 4   product_line      97979 non-null   object
 5   value             123683 non-null  float64
 6   date              132251 non-null  object
 7   product           132251 non-null  object
 8   month             132251 non-null  float64
 9   year              132251 non-null  float64
 10  quarter           132251 non-null  float64
dtypes: float64(5), object(6)
memory usage: 11.1+ MB

In [32]:
df['date'] = pd.to_datetime(df['date'], errors='coerce')

In [33]:
df["value"] = pd.to_numeric(df["value"], errors="coerce")

In [34]:
df.loc[
    ~(df['province'] == 'POLSKA') &
    ~(df['province'] == 'POLAND') &
    (df['province'].notnull()) &
    ~(df['value'] == 0) &
    ~(df['value'] == 3000) &
    (df['value'].notnull())     
    ]

,province,product_types,currency,product_group_id,product_line,value,date,product,month,year,quarter
0,SUBCARPATHIA,NaN,PLN,2.0,pork ham cooked - per 1kg,21.37,2013-03-01,pork ham cooked - per 1kg,3.0,2013.0,1.0
2,KUYAVIA-POMERANIA,NaN,PLN,2.0,barley groats sausage - per 1kg,3.55,2019-12-01,barley groats sausage - per 1kg,12.0,2019.0,4.0
3,LOWER SILESIA,NaN,PLN,2.0,dressed chickens - per 1kg,6.14,2019-02-01,dressed chickens - per 1kg,2.0,2019.0,1.0
4,WARMIA-MASURIA,NaN,PLN,2.0,Italian head cheese - per 1kg,5.63,2002-03-01,Italian head cheese - per 1kg,3.0,2002.0,1.0
5,HOLY CROSS,whole pickled cucumbers 0.9l - per 1pc.,PLN,1.0,NaN,0.28,2010-04-01,whole pickled cucumbers 0.9l - per 1pc.,4.0,2010.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...
132245,SILESIA,NaN,PLN,2.0,smoked bacon with ribs - per 1kg,15.95,2015-09-01,smoked bacon with ribs - per 1kg,9.0,2015.0,3.0
132246,SILESIA,NaN,PLN,2.0,barley groats sausage - per 1kg,4.50,2004-08-01,barley groats sausage - per 1kg,8.0,2004.0,3.0
132247,KUYAVIA-POMERANIA,NaN,PLN,2.0,pork meat (raw bacon) - per 1kg,12.15,2016-11-01,pork meat (raw bacon) - per 1kg,11.0,2016.0,4.0
132249,LESSER POLAND,NaN,PLN,4.0,plain mixed bread (wheat-rye) - per 1kg,3.05,2008-06-01,plain mixed bread (wheat-rye) - per 1kg,6.0,2008.0,2.0
132250,WARMIA-MASURIA,NaN,PLN,2.0,boneless beef (sirloin) - per 1kg,11.87,2000-11-01,boneless beef (sirloin) - per 1kg,11.0,2000.0,4.0

In [35]:
df['month'] = df['date'].dt.month
df['year'] = df['date'].dt.year
df['quarter'] = df['date'].dt.quarter
df['date'] = df['date'].dt.strftime('%Y-%m-01')

df.head()

,province,product_types,currency,product_group_id,product_line,value,date,product,month,year,quarter
0,SUBCARPATHIA,NaN,PLN,2.0,pork ham cooked - per 1kg,21.37,2013-03-01,pork ham cooked - per 1kg,3.0,2013.0,1.0
1,ŁÓDŹ,NaN,PLN,4.0,bread - per 1kg,NaN,2018-02-01,bread - per 1kg,2.0,2018.0,1.0
2,KUYAVIA-POMERANIA,NaN,PLN,2.0,barley groats sausage - per 1kg,3.55,2019-12-01,barley groats sausage - per 1kg,12.0,2019.0,4.0
3,LOWER SILESIA,NaN,PLN,2.0,dressed chickens - per 1kg,6.14,2019-02-01,dressed chickens - per 1kg,2.0,2019.0,1.0
4,WARMIA-MASURIA,NaN,PLN,2.0,Italian head cheese - per 1kg,5.63,2002-03-01,Italian head cheese - per 1kg,3.0,2002.0,1.0

In [36]:
df[[
    'province',
    'currency',
    'product_group_id',
    'value',
    'date',
    'product',
    'month',
    'year',
    'quarter'
]]

,province,currency,product_group_id,value,date,product,month,year,quarter
0,SUBCARPATHIA,PLN,2.0,21.37,2013-03-01,pork ham cooked - per 1kg,3.0,2013.0,1.0
1,ŁÓDŹ,PLN,4.0,NaN,2018-02-01,bread - per 1kg,2.0,2018.0,1.0
2,KUYAVIA-POMERANIA,PLN,2.0,3.55,2019-12-01,barley groats sausage - per 1kg,12.0,2019.0,4.0
3,LOWER SILESIA,PLN,2.0,6.14,2019-02-01,dressed chickens - per 1kg,2.0,2019.0,1.0
4,WARMIA-MASURIA,PLN,2.0,5.63,2002-03-01,Italian head cheese - per 1kg,3.0,2002.0,1.0
...,...,...,...,...,...,...,...,...,...
132247,KUYAVIA-POMERANIA,PLN,2.0,12.15,2016-11-01,pork meat (raw bacon) - per 1kg,11.0,2016.0,4.0
132248,ŁÓDŹ,PLN,3.0,0.00,2012-05-01,"beet sugar white, bagged - per 1kg",5.0,2012.0,2.0
132249,LESSER POLAND,PLN,4.0,3.05,2008-06-01,plain mixed bread (wheat-rye) - per 1kg,6.0,2008.0,2.0
132250,WARMIA-MASURIA,PLN,2.0,11.87,2000-11-01,boneless beef (sirloin) - per 1kg,11.0,2000.0,4.0
132251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
# Overwrite original CSV
df.to_csv(path, sep=';', index=False, encoding='UTF-8', decimal='.')

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132252 entries, 0 to 132251
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   province          132251 non-null  object
 1   product_types     34272 non-null   object
 2   currency          132251 non-null  object
 3   product_group_id  132251 non-null  float64
 4   product_line      97979 non-null   object
 5   value             123683 non-null  float64
 6   date              132251 non-null  object
 7   product           132251 non-null  object
 8   month             132251 non-null  float64
 9   year              132251 non-null  float64
 10  quarter           132251 non-null  float64
dtypes: float64(5), object(6)
memory usage: 11.1+ MB