# Adding a column

Following on the solution of the previous exercise, create a new column: **product** using **product_types** and **product_line**:

1. check that the **product_types** and **product_line** columns are complementary (an empty value in one column entails a non-empty value in the other).
1. create a new column: **product** using the values from the **product_types** column e.g. `df['product'] = df['product_types']`.
1. find non-empty values in the **product_line** column and enter them into the **product** column,
1. use a method of your choice to check if all values in the **product** column are non-empty.
1. remove duplicates from the table.
1. using the `to_csv` method save the data (we are going to use it later in the course), set separator=';' and `index=False`.<br>
Save the file as `product_prices_cleaned.csv`

The `read_csv` method is one of many that can be used to save a `DataFrame` as a **csv** file. Within the scope of this exercise we are interested in the following parameters.
- `sep`- row separator (default ','),
- `index`- is the index (row number by default) of the table to be saved as well (default: `True`).

Sample call:
```
df.to_csv(
    'filepath',
    sep=';', # separator setting
    index=False
)
```

In [57]:
import pandas as pd

df = pd.read_csv(
    r'C:\Users\UrosVukmanovic\CodersLab-Course-Python-Data-Analysis\Python Session_3\Session_3_-_exercise_files\01_Data\product_prices_cleaned_1.csv',
    sep=';',
    encoding='UTF-8',
    decimal='.'
)

df

C:\Users\UrosVukmanovic\AppData\Local\Temp\ipykernel_21748\1310159505.py:3: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

,province,product_types,currency,product_group_id,product_line,value,date
0,SUBCARPATHIA,NaN,PLN,2.0,pork ham cooked - per 1kg,21.37,2013-3
1,ŁÓDŹ,NaN,PLN,4.0,bread - per 1kg,NaN,2018-2
2,KUYAVIA-POMERANIA,NaN,PLN,2.0,barley groats sausage - per 1kg,3.55,2019-12
3,LOWER SILESIA,NaN,PLN,2.0,dressed chickens - per 1kg,6.14,2019-2
4,WARMIA-MASURIA,NaN,PLN,2.0,Italian head cheese - per 1kg,5.63,2002-3
...,...,...,...,...,...,...,...
149936,ŁÓDŹ,"beet sugar white, bagged - per 1kg",PLN,3.0,NaN,0.0,2012-5
149937,LESSER POLAND,NaN,PLN,4.0,plain mixed bread (wheat-rye) - per 1kg,3.05,2008-6
149938,WARMIA-MASURIA,NaN,PLN,2.0,boneless beef (sirloin) - per 1kg,11.87,2000-11
149939,MASOVIA,NaN,PLN,4.0,Masurian barley groats - per 1kg,0.16,2005-10
149940,NaN,NaN,NaN,NaN,NaN,PLN,NaN

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149941 entries, 0 to 149940
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   province          149940 non-null  object
 1   product_types     34272 non-null   object
 2   currency          149940 non-null  object
 3   product_group_id  149940 non-null  float64
 4   product_line      115668 non-null  object
 5   value             137089 non-null  object
 6   date              149940 non-null  object
dtypes: float64(1), object(6)
memory usage: 8.0+ MB

In [59]:
df.loc[
    (df['product_line'].isnull()) &
    (df['product_types'].isnull())
].shape[0]

1

In [60]:
df['product'] = df['product_types']
df

,province,product_types,currency,product_group_id,product_line,value,date,product
0,SUBCARPATHIA,NaN,PLN,2.0,pork ham cooked - per 1kg,21.37,2013-3,NaN
1,ŁÓDŹ,NaN,PLN,4.0,bread - per 1kg,NaN,2018-2,NaN
2,KUYAVIA-POMERANIA,NaN,PLN,2.0,barley groats sausage - per 1kg,3.55,2019-12,NaN
3,LOWER SILESIA,NaN,PLN,2.0,dressed chickens - per 1kg,6.14,2019-2,NaN
4,WARMIA-MASURIA,NaN,PLN,2.0,Italian head cheese - per 1kg,5.63,2002-3,NaN
...,...,...,...,...,...,...,...,...
149936,ŁÓDŹ,"beet sugar white, bagged - per 1kg",PLN,3.0,NaN,0.0,2012-5,"beet sugar white, bagged - per 1kg"
149937,LESSER POLAND,NaN,PLN,4.0,plain mixed bread (wheat-rye) - per 1kg,3.05,2008-6,NaN
149938,WARMIA-MASURIA,NaN,PLN,2.0,boneless beef (sirloin) - per 1kg,11.87,2000-11,NaN
149939,MASOVIA,NaN,PLN,4.0,Masurian barley groats - per 1kg,0.16,2005-10,NaN
149940,NaN,NaN,NaN,NaN,NaN,PLN,NaN,NaN

Svaki izabrani red (product gdje je mask True) dobije vrijednost iz df['product_line'] sa istim indeksom (tj. iz istog reda).

Ako umjesto Series proslijediš niz bez indeksa (npr. df['product_line'].values), tada se vrijednosti dodjeljuju pozicijski (prvi True dobije prvu vrijednost, drugi True drugu, itd.) — to može promašiti ako su redovi neselektivni ili indeks nije u nizu.

In [61]:
df.loc[df['product'].isnull(), 'product'] = df['product_line']
df

,province,product_types,currency,product_group_id,product_line,value,date,product
0,SUBCARPATHIA,NaN,PLN,2.0,pork ham cooked - per 1kg,21.37,2013-3,pork ham cooked - per 1kg
1,ŁÓDŹ,NaN,PLN,4.0,bread - per 1kg,NaN,2018-2,bread - per 1kg
2,KUYAVIA-POMERANIA,NaN,PLN,2.0,barley groats sausage - per 1kg,3.55,2019-12,barley groats sausage - per 1kg
3,LOWER SILESIA,NaN,PLN,2.0,dressed chickens - per 1kg,6.14,2019-2,dressed chickens - per 1kg
4,WARMIA-MASURIA,NaN,PLN,2.0,Italian head cheese - per 1kg,5.63,2002-3,Italian head cheese - per 1kg
...,...,...,...,...,...,...,...,...
149936,ŁÓDŹ,"beet sugar white, bagged - per 1kg",PLN,3.0,NaN,0.0,2012-5,"beet sugar white, bagged - per 1kg"
149937,LESSER POLAND,NaN,PLN,4.0,plain mixed bread (wheat-rye) - per 1kg,3.05,2008-6,plain mixed bread (wheat-rye) - per 1kg
149938,WARMIA-MASURIA,NaN,PLN,2.0,boneless beef (sirloin) - per 1kg,11.87,2000-11,boneless beef (sirloin) - per 1kg
149939,MASOVIA,NaN,PLN,4.0,Masurian barley groats - per 1kg,0.16,2005-10,Masurian barley groats - per 1kg
149940,NaN,NaN,NaN,NaN,NaN,PLN,NaN,NaN

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149941 entries, 0 to 149940
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   province          149940 non-null  object
 1   product_types     34272 non-null   object
 2   currency          149940 non-null  object
 3   product_group_id  149940 non-null  float64
 4   product_line      115668 non-null  object
 5   value             137089 non-null  object
 6   date              149940 non-null  object
 7   product           149940 non-null  object
dtypes: float64(1), object(7)
memory usage: 9.2+ MB

In [63]:
df.drop_duplicates().to_csv(
    r'C:\Users\UrosVukmanovic\CodersLab-Course-Python-Data-Analysis\Python Session_3\Session_3_-_exercise_files\01_Data\product_prices_cleaned_2.csv',
    sep = ';',
    decimal = '.',
    index = False
)