# Exercise
Read the file: `product_prices.csv` (separator ';', decimal separator '.') and do the following exercises:

1. Using the `columns` method modify the names of columns to be: `'province', 'product_types', 'currency', 'group_id', 'product_line', 'value', 'date'`<br>
1. Determine the following positional statistics: mean, standard deviation, percentiles: 0, 10%, 20%, 30%, 40%, 50%, 60%, 70%, 80%, 90%, 100%.<br>Do the exercise **in two versions**: using dedicated functions and `describe`.
1. Do you agree with this way of generating these values? Why?

In [26]:
import pandas as pd # library import

df_raw = pd.read_csv(
    r'..\01_data\product_prices.csv',  # path to data file
    sep=';',  # column separator
    decimal=','  # character separating the whole and fractional parts of a number
)

In [28]:
df_raw.columns = ['province', 'product_types', 'currency', 'group_id', 'product_line', 'value', 'date']

In [29]:
df_raw.info

<bound method DataFrame.info of                  province                       product_types currency  \
0            SUBCARPATHIA                                 NaN      PLN
1                    ŁÓDŹ                                 NaN      PLN
2       KUYAVIA-POMERANIA                                 NaN      PLN
3           LOWER SILESIA                                 NaN      PLN
4          WARMIA-MASURIA                                 NaN      PLN
...                   ...                                 ...      ...
149935  KUYAVIA-POMERANIA                                 NaN      PLN
149936               ŁÓDŹ  beet sugar white, bagged - per 1kg      PLN
149937      LESSER POLAND                                 NaN      PLN
149938     WARMIA-MASURIA                                 NaN      PLN
149939            MASOVIA                                 NaN      PLN

        group_id                             product_line  value     date
0              2                pork ham cooked - per 1kg  21.37   2013-3
1              4                          bread - per 1kg    NaN   2018-2
2              2          barley groats sausage - per 1kg   3.55  2019-12
3              2               dressed chickens - per 1kg   6.14   2019-2
4              2            Italian head cheese - per 1kg   5.63   2002-3
...          ...                                      ...    ...      ...
149935         2         pork  meat (raw bacon) - per 1kg  12.15  2016-11
149936         3                                      NaN    0.0   2012-5
149937         4  plain mixed bread (wheat-rye) - per 1kg   3.05   2008-6
149938         2        boneless beef (sirloin) - per 1kg  11.87  2000-11
149939         4         Masurian barley groats - per 1kg   0.16  2005-10

[149940 rows x 7 columns]>

In [30]:
df_raw.describe()

            group_id
count  149940.000000
mean        2.571429
std         1.022206
min         1.000000
25%         2.000000
50%         2.000000
75%         4.000000
max         4.000000

In [33]:

df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149940 entries, 0 to 149939
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   province       149940 non-null  object
 1   product_types  34272 non-null   object
 2   currency       149940 non-null  object
 3   group_id       149940 non-null  int64
 4   product_line   115668 non-null  object
 5   value          137088 non-null  object
 6   date           149940 non-null  object
dtypes: int64(1), object(6)
memory usage: 8.0+ MB

In [35]:
df_raw['value'] = df_raw['value'].astype(float)
df_raw['value'].dtype

dtype('float64')

In [36]:
df_raw['value'].mean()

np.float64(6.615226740294512)

In [37]:
df_raw['value'].quantile([0, 0.1, 0.5, 0.75, 1])

0.00       0.00
0.10       0.00
0.50       3.09
0.75      10.92
1.00    3000.00
Name: value, dtype: float64

In [ ]:
import pandas as pd # library import

df_raw = pd.read_csv(
    r'..\01_data\product_prices.csv',  # path to data file
    sep=';',  # column separator
    decimal=','  # character separating the whole and fractional parts of a number
)

In [ ]:
df_raw.shape

(149940, 7)

In [ ]:
df_raw.head(5) # displays the first 5 rows of the table

,Name,Goods types,Measurement unit,Group ID,Product types,Value,Date
0,SUBCARPATHIA,NaN,PLN,2,pork ham cooked - per 1kg,21.37,2013-3
1,ŁÓDŹ,NaN,PLN,4,bread - per 1kg,NaN,2018-2
2,KUYAVIA-POMERANIA,NaN,PLN,2,barley groats sausage - per 1kg,3.55,2019-12
3,LOWER SILESIA,NaN,PLN,2,dressed chickens - per 1kg,6.14,2019-2
4,WARMIA-MASURIA,NaN,PLN,2,Italian head cheese - per 1kg,5.63,2002-3

In [ ]:
df_raw.tail(10)

,Name,Goods types,Measurement unit,Group ID,Product types,Value,Date
149930,WARMIA-MASURIA,NaN,PLN,4,"Poznan wheat flour, bagged - per 1kg",0.99,2010-10
149931,POMERANIA,NaN,PLN,2,pork belly cooked - per 1kg,14.48,1999-10
149932,MASOVIA,NaN,PLN,2,"salted herring, non-dressed - per 1kg",0.0,2001-3
149933,SILESIA,NaN,PLN,2,smoked bacon with ribs - per 1kg,15.95,2015-9
149934,SILESIA,NaN,PLN,2,barley groats sausage - per 1kg,4.5,2004-8
149935,KUYAVIA-POMERANIA,NaN,PLN,2,pork meat (raw bacon) - per 1kg,12.15,2016-11
149936,ŁÓDŹ,"beet sugar white, bagged - per 1kg",PLN,3,NaN,0.0,2012-5
149937,LESSER POLAND,NaN,PLN,4,plain mixed bread (wheat-rye) - per 1kg,3.05,2008-6
149938,WARMIA-MASURIA,NaN,PLN,2,boneless beef (sirloin) - per 1kg,11.87,2000-11
149939,MASOVIA,NaN,PLN,4,Masurian barley groats - per 1kg,0.16,2005-10

In [ ]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149940 entries, 0 to 149939
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Name              149940 non-null  object
 1   Goods types       34272 non-null   object
 2   Measurement unit  149940 non-null  object
 3   Group ID          149940 non-null  int64
 4   Product types     115668 non-null  object
 5   Value             137088 non-null  object
 6   Date              149940 non-null  object
dtypes: int64(1), object(6)
memory usage: 8.0+ MB

In [ ]:
df_raw.columns

Index(['Name', 'Goods types', 'Measurement unit', 'Group ID', 'Product types',
       'Value', 'Date'],
      dtype='object')

In [ ]:
df_raw["Name"]

0              SUBCARPATHIA
1                      ŁÓDŹ
2         KUYAVIA-POMERANIA
3             LOWER SILESIA
4            WARMIA-MASURIA
                ...
149935    KUYAVIA-POMERANIA
149936                 ŁÓDŹ
149937        LESSER POLAND
149938       WARMIA-MASURIA
149939              MASOVIA
Name: Name, Length: 149940, dtype: object

In [ ]:
df_raw[['Name', 'Value']]

                     Name  Value
0            SUBCARPATHIA  21.37
1                    ŁÓDŹ    NaN
2       KUYAVIA-POMERANIA   3.55
3           LOWER SILESIA   6.14
4          WARMIA-MASURIA   5.63
...                   ...    ...
149935  KUYAVIA-POMERANIA  12.15
149936               ŁÓDŹ    0.0
149937      LESSER POLAND   3.05
149938     WARMIA-MASURIA  11.87
149939            MASOVIA   0.16

[149940 rows x 2 columns]

In [ ]:
import pandas as pd
df_raw = pd.read_csv(
    r'..\01_data\product_prices.csv',  # path to data file
    sep=';',  # column separator
    decimal=','  # character separating the whole and fractional parts of a number
)

In [ ]:
col = df_raw['Value'].head() # we pull the Value column out of the frame - it will be useful for presenting sub-stat operations
#type(col) # we check that the column type is actually series

In [ ]:
col

0    21.37
1      NaN
2     3.55
3     6.14
4     5.63
Name: Value, dtype: object

In [ ]:
import pandas as pd

df_raw = pd.read_csv(
    r'..\01_data\raw\preserves.csv',  # path to data file
    sep=';',  # column separator
    decimal=','  # character separating the whole and fractional parts of a number
)

In [ ]:
df_raw['Value'].mean() # determine the average price for the pickups

np.float64(2.1737464985994395)

In [ ]:
# here we have an example of data with mean = 0
data1 = pd.Series([-1, 0, 1])
data2 = pd.Series([-10, -90, 0, 0, 100])


print("Data 1 mean: {}; std: {}".format(
    data1.mean(),
    data1.std()
))

print("Data 2 mean: {}; std: {}".format(
    data2.mean(),
    data2.std()
))

Data 1 mean: 0.0; std: 1.0
Data 2 mean: 0.0; std: 67.45368781616021

In [ ]:
df_raw['Value'].quantile([0, 0.1, 0.5, 0.75, 1])

0.00     0.000
0.10     0.000
0.50     1.775
0.75     3.130
1.00    15.590
Name: Value, dtype: float64

In [ ]:
df_raw['Value'].describe()

count    1428.000000
mean        2.173746
std         2.783598
min         0.000000
25%         0.000000
50%         1.775000
75%         3.130000
max        15.590000
Name: Value, dtype: float64

## Comment regarding the correctness of the exercise
Summarizing a dataset in this way is not entirely correct because all groups of products (preserves, meat, oat and other products) were treated as comparable. Moreover, because the data is formatted as a time series, all dates were treated the same.

This is commonly known as comparing oranges to apples. These statistics should at least be performed separately for each of the groups, and ideally sub-divided by quarter of the year.